# Modified from https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
name: Test building ctsm-docs Docker image

# Configures this workflow to run every time a change in the Docker container setup is pushed to the master branch
on:
  push:
    paths:
      - 'doc/ctsm-docs_container/**'

  pull_request:
    paths:
      - 'doc/ctsm-docs_container/**'

  workflow_dispatch:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/ctsm-docs

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-image-and-test-docs:
    uses: ./.github/workflows/docker-image-build-common.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/ctsm-docs
    secrets: inherit
