name: Test building docs with ctsm_pylib

on:
  push:
    paths:
      - 'python/conda_env_ctsm_py.txt'

  pull_request:
    paths:
      - 'python/conda_env_ctsm_py.txt'

  schedule:
    # 8 am every Monday UTC
    - cron: '0 8 * * 1'

  workflow_dispatch:

permissions:
  contents: read
jobs:
  test-build-docs-ctsm_pylib:
    if: ${{ always() }}
    name: Test building documentation with ctsm_pylib
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: true
      conda_env_file: python/conda_env_ctsm_py.yml
      conda_env_name: ctsm_pylib


