name: docs

on:
  push:
    paths:
      - 'doc/**'

  pull_request:
    paths:
      - 'doc/**'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs:
    if: ${{ always() }}
    name: Test building documentation without ctsm_pylib or container
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: false

  test-build-docs-container:
    if: ${{ always() }}
    name: Test building documentation with container
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout doc-builder external
        run: |
          bin/git-fleximod update doc-builder

      - name: Build docs using container
        id: build-docs
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c -d
