name: docs

on:
  push:
    paths:
      - 'doc/**'
      - 'python/conda_env_ctsm_py.txt'

  pull_request:
    paths:
      - 'doc/**'
      - 'python/conda_env_ctsm_py.txt'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs:
    if: ${{ always() }}
    name: Test building documentation without ctsm_pylib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Checkout externals, including doc-builder
        run: |
          bin/git-fleximod update --optional
      
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'  # needs to be coordinated with version in python/conda_env_ctsm_py.txt

      # Set up for installing Python requirements
      # Based on  https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('doc/ctsm-docs_container/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: |
          pip install -r doc/ctsm-docs_container/requirements.txt

      - name: Build Sphinx docs with makefile
        run: |
          make SPHINXOPTS="-W --keep-going" BUILDDIR=${PWD}/_build -C doc/ html

      - name: Build Sphinx docs with doc-builder
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c

  test-build-docs-ctsm_pylib:
    if: ${{ always() }}
    name: Test building documentation with ctsm_pylib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Set up the conda environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ctsm_pylib
          environment-file: python/conda_env_ctsm_py.yml
          channels: conda-forge
          auto-activate-base: false

      - name: Build Sphinx docs with makefile
        continue-on-error: true
        run: |
          conda run -n ctsm_pylib make SPHINXOPTS="-W --keep-going" BUILDDIR=${PWD}/_build -C doc/ html

      - name: Checkout externals, including doc-builder
        run: |
          bin/git-fleximod update --optional

      - name: Build Sphinx docs with doc-builder
        continue-on-error: true
        run: |
          cd doc && conda run -n ctsm_pylib ./build_docs -b ${PWD}/_build -c

