name: docs

on:
  push:
    paths:
      - 'doc/**'

  pull_request:
    paths:
      - 'doc/**'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs:
    if: ${{ always() }}
    name: Test building documentation without ctsm_pylib
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: false
