name: docs

on:
  push:
    paths:
      - 'python/conda_env_ctsm_py.txt'

  pull_request:
    paths:
      - 'python/conda_env_ctsm_py.txt'

  workflow_dispatch:

permissions:
  contents: read
jobs:
  test-build-docs-ctsm_pylib:
    if: ${{ always() }}
    name: Test building documentation with ctsm_pylib
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: true
      conda_env_file: python/conda_env_ctsm_py.yml
      conda_env_name: ctsm_pylib

  test-build-docs-container:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout doc-builder external
        run: |
          bin/git-fleximod update doc-builder

      - name: Build docs using container
        id: build-docs
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c -d


