name: docs-ctsm_pylib

on:
  push:
    paths:
      - 'doc/**'
      - 'python/conda_env_ctsm_py.yml'

  pull_request:
    paths:
      - 'doc/**'
      - 'python/conda_env_ctsm_py.yml'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  # Sam Rabin, 2025-04-17: This could theoretically be a separate job in docs.yml. However, putting it there breaks my ability to
  # run EITHER job on my Mac using act.
  test-build-docs-ctsm_pylib:
    if: ${{ always() }}
    name: Test building documentation with ctsm_pylib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Set up the conda environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ctsm_pylib
          environment-file: python/conda_env_ctsm_py.yml
          channels: conda-forge
          auto-activate-base: false

      - name: Build Sphinx docs with makefile
        continue-on-error: true
        run: |
          conda run -n ctsm_pylib make SPHINXOPTS="-W --keep-going" BUILDDIR=${PWD}/_build -C doc/ html

      - name: Checkout externals, including doc-builder
        run: |
          bin/git-fleximod update --optional

      - name: Build Sphinx docs with doc-builder
        continue-on-error: true
        run: |
          cd doc && conda run -n ctsm_pylib ./build_docs -b ${PWD}/_build -c
