name: Run Python tests

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'python/**'
      - 'cime_config/SystemTests/**'
      - 'cime_config/buildlib/**'
      - 'cime_config/buildnml/**'
  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'python/**'
      - 'cime_config/SystemTests/**'
      - 'cime_config/buildlib/**'
      - 'cime_config/buildnml/**'

jobs:
  python-unit-tests:
    runs-on: ubuntu-24.04-arm
    # container:
    #   image: ghcr.io/samsrabin/ctsm/ctsm_pylib-container:latest
    #   options: --user 1001:121
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Run Python unit tests check
      - name: Run Python unit tests
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/samsrabin/ctsm/ctsm_pylib-container:latest
            options: -v ${{ github.workspace }}:/home/mambauser
            run: |
                cd python
                ./run_ctsm_py_tests -u

  python-lint-and-black:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up the conda environment
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ctsm_pylib
          environment-file: python/conda_env_ctsm_py.yml
          channels: conda-forge
          auto-activate-base: false

      # Run pylint check
      - name: Run pylint
        run: |
          cd python
          conda run -n ctsm_pylib make lint

      # Run black check
      - name: Run black
        # Run this step even if previous step(s) failed
        if: success() || failure()
        run: |
          cd python
          conda run -n ctsm_pylib make black
